# https://ci.appveyor.com/project/olegsych/inspector/settings/yaml

version: 0.1.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

skip_tags: true

image: Visual Studio 2019

clone_script:
- cmd: git clone --recurse-submodules -c core.symlinks=true https://github.com/olegsych/inspector.git .\

build_script:
- cmd: dotnet build .\Inspector.sln -nologo -logger:"C:\Program Files\AppVeyor\BuildAgent\dotnetcore\Appveyor.MSBuildLogger.dll"

test_script:
- cmd: dotnet test .\tst\Inspector.Tests.csproj

after_test:
- cmd: dotnet pack .\src\Inspector.csproj --include-symbols

artifacts:
- path: bin\debug\*.*nupkg

deploy:
- provider: NuGet
  api_key:
    secure: O4dRVPV5hv283cF20s1Ab8Ba+RAaNeaDTxjgPMURfX1/f8riqFMO8f5gaCJkgCPH