name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      PACKAGES: bin/Release/Inspector.*.nupkg
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0
      - run: dotnet build Inspector.slnx
      - run: dotnet test --no-build tst/Tests.csproj
      - run: dotnet pack src/Inspector.csproj
      - uses: actions/upload-artifact@v6
        with:
          name: packages
          path: ${{ env.PACKAGES }}
      - run: |
          dir "$env:PACKAGES" |
          %{ dotnet nuget push $_ --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate }
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      - name: Tag commit with package version
        run: |
          $version = (dir $env:PACKAGES | select -First 1).Name -replace 'Inspector\.(.+)\.nupkg','$1'
          $tag = "v$version"
          git fetch --tags
          if (-not (git tag -l $tag)) {
            git tag $tag
            git push origin $tag
          }
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
