name: publish

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: Build workflow run ID to publish packages from
        required: true

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: packages
          path: packages
          run-id: ${{ inputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: dotnet nuget push packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
